# Copyright (c) 2015 Intel Corporation. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.
version: 19.6.2.{build}
clone_folder: c:\projects\realsense-extensions-crosswalk\src\extensions
init:
- cmd: git config --global core.autocrlf input
environment:
  DEPOT_TOOLS_WIN_TOOLCHAIN: 0
  XWALK_CHANNEL: beta
  XWALK_VERSION: 19.49.514.1
  LIBPXC_VERSION: 568e4ecc969b4663e82034e71d08efdd5fa77e1a
install:
- cmd: >-
    git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git c:\projects\realsense-extensions-crosswalk\src\third_party\depot_tools

    set PATH=%PATH%;c:\projects\realsense-extensions-crosswalk\src\third_party\depot_tools

    mkdir c:\projects\xwalk

    cd c:\projects\xwalk

    curl -fsS -o crosswalk64-%XWALK_VERSION%.zip https://download.01.org/crosswalk/releases/crosswalk/windows/%XWALK_CHANNEL%/%XWALK_VERSION%/crosswalk64-%XWALK_VERSION%.zip

    set XWALK_HOME=c:\projects\xwalk\crosswalk64-%XWALK_VERSION%.zip

    7z x crosswalk64-%XWALK_VERSION%.zip

    npm install -g https://github.com/crosswalk-project/crosswalk-app-tools.git

    set PATH=%PATH%;C:\Program Files (x86)\WiX Toolset v3.10\bin

    cd c:\projects\realsense-extensions-crosswalk

    gclient config --spec=solutions=[{'name':'src','url':'https://github.com/crosswalk-project/crosswalk-extensions-sdk.git','deps_file':'DEPS','managed':True,'custom_deps':{'extensions/third_party/libpxc':'https://github.com/crosswalk-project/libpxc.git@%LIBPXC_VERSION%'},'safesync_url':'',},]

    gclient sync

    python src\extensions\sample\sample_bower_update.py
before_build:
- cmd: >-
    set PATH=%PATH%;c:\Python27\Scripts

    cd c:\projects\realsense-extensions-crosswalk

    git clone https://github.com/google/closure-linter.git

    cd closure-linter

    python .\setup.py install

    cd ..\src\extensions

    python ..\tools\lint.py
build_script:
- cmd: >-
    cd c:\projects\realsense-extensions-crosswalk\src

    gn gen out\Release_x64_gn --args="is_debug=false"

    ninja -C out\Release_x64_gn sample_app
after_build:
- cmd: >-
    cd c:\projects\realsense-extensions-crosswalk\src\out\Release_x64_gn

    7z a realsense_extensions.zip realsense_extensions

    appveyor PushArtifact realsense_extensions.zip

    7z a rs_sample_installer.zip org.crosswalk_project.rs_sample_with_rssdk_runtime_*

    appveyor PushArtifact rs_sample_installer.zip

    7z a rs_sample_polymer_installer.zip org.crosswalk_project.rs_sample_polymer_with_rssdk_runtime_*

    appveyor PushArtifact rs_sample_polymer_installer.zip
deploy:
  description: 'Release Description'
  provider: GitHub
  auth_token:
    secure: x7Q/400f4Ng1G+6j+c70wrgd866E3lDV1buKeHZPdftRo/cog1kP3CFE612n/kP5
  draft: true
  prerelease: true
  on:
    appveyor_repo_tag: true
test: off

artifacts:
    - path: realsense_extensions.zip
      name: RealSense Extensions for crosswalk

    - path: rs_sample_installer.zip
      name: RealSense Sample App Installer

    - path: rs_sample_polymer_installer.zip
      name: RealSense Sample App (Polymer) Installer
