// Copyright 2016 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

namespace common{
  enum ErrorCode {
    feature_unsupported,
    param_unsupported,
    invalid_photo,
    init_failed,
    exec_failed
  };

  dictionary DEPError {
    ErrorCode error;
    DOMString message;
  };
};
