// Copyright 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_COMMON_UTILS_H_
#define REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_COMMON_UTILS_H_

#include <string>

#include "base/memory/scoped_ptr.h"
#include "base/values.h"
// This file is auto-generated by common.idl
#include "common.h"  // NOLINT
// This file is auto-generated by depth_photo.idl
#include "depth_photo.h" // NOLINT
#include "realsense/enhanced_photography/win/enhanced_photography_instance.h"
#include "third_party/libpxc/include/pxcphoto.h"

namespace realsense {
namespace enhanced_photography {

using namespace jsapi::common;  // NOLINT

bool CopyImageToBinaryMessage(PXCImage* image,
                              scoped_ptr<uint8[]>& binary_message,  // NOLINT
                              size_t* length);
void CreateDepthPhotoObject(EnhancedPhotographyInstance* instance,
                            PXCPhoto* pxcphoto,
                            jsapi::depth_photo::Photo* photo);
scoped_ptr<base::ListValue> CreateErrorResult(ErrorCode error);
scoped_ptr<base::ListValue> CreateErrorResult(ErrorCode error,
                                              const std::string& message);
scoped_ptr<base::ListValue> CreateSuccessResult();
void GetBinaryValueFromArgs(base::ListValue* args, base::BinaryValue** value);

}  // namespace enhanced_photography
}  // namespace realsense

#endif  // REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_COMMON_UTILS_H_
