// Copyright 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_DEPTH_REFOCUS_OBJECT_H_
#define REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_DEPTH_REFOCUS_OBJECT_H_

// This file is auto-generated by depth_refocus.idl
#include "depth_refocus.h" // NOLINT

#include "realsense/enhanced_photography/win/enhanced_photography_instance.h"
#include "third_party/libpxc/include/pxcenhancedphoto.h"
#include "third_party/libpxc/include/pxcsession.h"

namespace realsense {
namespace enhanced_photography {

using xwalk::common::XWalkExtensionFunctionInfo;
using namespace jsapi::depth_refocus; // NOLINT

class DepthRefocusObject : public xwalk::common::BindingObject {
 public:
  explicit DepthRefocusObject(EnhancedPhotographyInstance* instance);
  ~DepthRefocusObject() override;

 private:
  void OnInit(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnApply(scoped_ptr<XWalkExtensionFunctionInfo> info);

  EnhancedPhotographyInstance* instance_;
  PXCSession* session_;
  PXCEnhancedPhoto::DepthRefocus* depth_refocus_;
};

}  // namespace enhanced_photography
}  // namespace realsense

#endif  // REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_DEPTH_REFOCUS_OBJECT_H_
