// Copyright 2016 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_DEPTH_MASK_OBJECT_H_
#define REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_DEPTH_MASK_OBJECT_H_

// This file is auto-generated by depth_mask.idl
#include "depth_mask.h" // NOLINT

#include "realsense/enhanced_photography/win/enhanced_photography_instance.h"
#include "third_party/libpxc/include/pxcenhancedphoto.h"
#include "third_party/libpxc/include/pxcsession.h"

namespace realsense {
namespace enhanced_photography {

using xwalk::common::XWalkExtensionFunctionInfo;
using namespace jsapi::depth_mask; // NOLINT

class DepthMaskObject : public xwalk::common::BindingObject {
 public:
  explicit DepthMaskObject(EnhancedPhotographyInstance* instance);
  ~DepthMaskObject() override;

 private:
  void OnInit(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnComputeFromCoordinate(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnComputeFromThreshold(scoped_ptr<XWalkExtensionFunctionInfo> info);

  EnhancedPhotographyInstance* instance_;
  PXCSession* session_;
  PXCEnhancedPhoto::DepthMask* depth_mask_;
  scoped_ptr<uint8[]> binary_message_;
  size_t binary_message_size_;
};

}  // namespace enhanced_photography
}  // namespace realsense

#endif  // REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_DEPTH_MASK_OBJECT_H_
