// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// EnhancedPhotography API
namespace depth_photo {
  enum PixelFormat {
    RGB32,
    DEPTH,
    DEPTH_F32,
    Y8
  };

  dictionary Image {
    PixelFormat format;
    long width;
    long height;
    long[] data;
  };

  dictionary MaskImage{
    PixelFormat format;
    long width;
    long height;
    double[] data;
  };

  dictionary Photo{
    DOMString objectId;
  };

  callback ArrayBufferPromise = void(ArrayBuffer buffer, DOMString error);
  callback ImagePromise = void(Image image, DOMString error);
  callback Promise = void(DOMString success, DOMString error);
  callback PhotoPromise = void(Photo photo, DOMString error);

  interface Functions {
    static void loadXDM(ArrayBuffer buffer, Promise promise);
    static void saveXDM(ArrayBufferPromise promise);
    static void queryContainerImage(ImagePromise promise);
    static void queryColorImage(ImagePromise promise);
    static void queryDepthImage(ImagePromise promise);
    static void queryRawDepthImage(ImagePromise promise);
    static void setContainerImage(ArrayBuffer image, Promise promise);
    static void setColorImage(ArrayBuffer image, Promise promise);
    static void setDepthImage(ArrayBuffer image, Promise promise);
    static void setRawDepthImage(ArrayBuffer  image, Promise promise);
    static void clone(PhotoPromise promise);

    [nodoc] static DepthPhoto depthPhotoConstructor(DOMString objectId);
  };
};
