// Copyright 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_ENHANCED_PHOTOGRAPHY_OBJECT_H_
#define REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_ENHANCED_PHOTOGRAPHY_OBJECT_H_

// This file is auto-generated by enhanced_photography.idl
#include "enhanced_photography.h" // NOLINT

#include "realsense/enhanced_photography/win/enhanced_photography_instance.h"
#include "third_party/libpxc/include/pxcenhancedphoto.h"
#include "third_party/libpxc/include/pxcsession.h"

namespace realsense {
namespace enhanced_photography {

using xwalk::common::XWalkExtensionFunctionInfo;
using namespace jsapi::enhanced_photography; // NOLINT

class EnhancedPhotographyObject : public xwalk::common::BindingObject {
 public:
  explicit EnhancedPhotographyObject(EnhancedPhotographyInstance* instance);
  ~EnhancedPhotographyObject() override;

 private:
  void OnMeasureDistance(scoped_ptr<XWalkExtensionFunctionInfo> info);

  void ReleaseResources();

  PXCSession* session_;
  PXCEnhancedPhoto* ep_;

  EnhancedPhotographyInstance* instance_;
};

}  // namespace enhanced_photography
}  // namespace realsense

#endif  // REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_ENHANCED_PHOTOGRAPHY_OBJECT_H_
