// Copyright 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_MEASUREMENT_OBJECT_H_
#define REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_MEASUREMENT_OBJECT_H_

// This file is auto-generated by measurement.idl
#include "measurement.h"  // NOLINT

#include "realsense/enhanced_photography/win/enhanced_photography_instance.h"
#include "third_party/libpxc/include/pxcenhancedphoto.h"
#include "third_party/libpxc/include/pxcsession.h"

namespace realsense {
namespace enhanced_photography {

using xwalk::common::XWalkExtensionFunctionInfo;
using namespace jsapi::measurement;  // NOLINT

class MeasurementObject : public xwalk::common::BindingObject {
 public:
  explicit MeasurementObject(EnhancedPhotographyInstance* instance);
  ~MeasurementObject() override;

 private:
  void OnMeasureDistance(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnMeasureUADistance(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnQueryUADataSize(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnQueryUAData(scoped_ptr<XWalkExtensionFunctionInfo> info);

  void FillMeasureData(MeasureData* measureData,
                       PXCEnhancedPhoto::Measurement::MeasureData* data);
  void ReleaseResources();

  PXCSession* session_;
  PXCEnhancedPhoto::Measurement* measurement_;

  EnhancedPhotographyInstance* instance_;
};

}  // namespace enhanced_photography
}  // namespace realsense

#endif  // REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_MEASUREMENT_OBJECT_H_
