// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Paster interface
namespace paster {
  dictionary StickerData {
    double height;
    double rotation;
    boolean isCenter;
  };

  dictionary PasteEffects {
    boolean matchIllumination;
    double transparency;
    double embossHighFreqPass;
    boolean shadingCorrection;
    boolean colorCorrection;
  };

  callback ImagePromise = void(depth_photo.Image image, DOMString error);
  callback Promise = void(DOMString success, DOMString error);
  callback PhotoPromise = void(depth_photo.Photo photo, DOMString error);

  interface Functions {
    static void getPlanesMap(ImagePromise promise);
    static void setSticker(depth_photo.Image sticker, depth_photo.Point coordinates, StickerData params, optional PasteEffects effects, Promise promise);
    static void paste(PhotoPromise promise);
    static void previewSticker(ImagePromise promise);

    [nodoc] static Paster pasterConstructor(DOMString objectId, depth_photo.Photo photo);
  };
};
