// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// PhotoCapture interface
namespace photo_capture {
  dictionary ErrorEvent {
    DOMString error;
  };

  dictionary DepthQualityEvent {
    photo_utils.DepthMapQuality quality;
  };

  callback ImagePromise = void(depth_photo.Image image, DOMString error);
  callback PhotoPromise = void(depth_photo.Photo photo, DOMString error);

  interface Events {
    static void onerror();
    static void ondepthquality();
  };

  interface Functions {
    static void enableDepthStream(DOMString camera);
    static void disableDepthStream();
    static void getDepthImage(ImagePromise promise);
    static void takePhoto(PhotoPromise promise);
    
    [nodoc] static PhotoCapture photoCaptureConstructor(DOMString objectId);
  };
};
