// Copyright 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#ifndef REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_PHOTO_UTILS_OBJECT_H_
#define REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_PHOTO_UTILS_OBJECT_H_

// This file is auto-generated by photo_utils.idl
#include "photo_utils.h" // NOLINT

#include "realsense/enhanced_photography/win/enhanced_photography_instance.h"
#include "third_party/libpxc/include/pxcenhancedphoto.h"
#include "third_party/libpxc/include/pxcsession.h"
#include "third_party/libpxc/include/pxcphoto.h"

namespace realsense {
namespace enhanced_photography {

using xwalk::common::XWalkExtensionFunctionInfo;
using namespace jsapi::photo_utils; // NOLINT

class PhotoUtilsObject : public xwalk::common::BindingObject {
 public:
  explicit PhotoUtilsObject(EnhancedPhotographyInstance* instance);
  ~PhotoUtilsObject() override;

 private:
  void OnColorResize(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnCommonFOV(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnDepthResize(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnEnhanceDepth(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnGetDepthQuality(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnPhotoCrop(scoped_ptr<XWalkExtensionFunctionInfo> info);
  void OnPhotoRotate(scoped_ptr<XWalkExtensionFunctionInfo> info);

  EnhancedPhotographyInstance* instance_;
  PXCSession* session_;
  PXCEnhancedPhoto::PhotoUtils* photo_utils_;
};

}  // namespace enhanced_photography
}  // namespace realsense

#endif  // REALSENSE_ENHANCED_PHOTOGRAPHY_WIN_PHOTO_UTILS_OBJECT_H_
