// Copyright 2016 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// Common interface
namespace common {
  enum ErrorCode {
    feature_unsupported,
    param_unsupported,
    photo_invalid,
    init_failed,
    exec_failed
  };

  dictionary RSError {
    ErrorCode error;
    DOMString message;
  };

  // https://heycam.github.io/webidl/#idl-DOMException-error-names
  enum ErrorName {
    IndexSizeError,
    HierarchyRequestError,
    WrongDocumentError,
    InvalidCharacterError,
    NoModificationAllowedError,
    NotFoundError,
    NotSupportedError,
    InUseAttributeError,
    InvalidStateError,
    SyntaxError,
    InvalidModificationError,
    NamespaceError,
    InvalidAccessError,
    SecurityError,
    NetworkError,
    AbortError,
    URLMismatchError,
    QuotaExceededError,
    TimeoutError,
    InvalidNodeTypeError,
    DataCloneError,
    EncodingError,
    NotReadableError,
    UnknownError,
    ConstraintError,
    DataError,
    TransactionInactiveError,
    ReadOnlyError,
    VersionError,
    OperationError,
    NotAllowedError
  };

  dictionary DOMException {
    DOMString message;
    ErrorName name;
  };
};
