// Copyright (c) 2016 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "realsense/hand/win/hand_instance.h"

#include <string>

// This file is auto-generated by hand_module.idl
#include "hand_module.h"  // NOLINT

#include "base/json/json_string_value_serializer.h"
#include "realsense/hand/win/hand_module_object.h"

namespace realsense {
namespace hand {

using namespace xwalk::common; // NOLINT
using realsense::jsapi::hand_module::HandModuleConstructor::Params;

HandInstance::HandInstance()
    : handler_(this),
      store_(&handler_),
      hand_ext_thread_("HandExtensionThread") {
  hand_ext_thread_.Start();
  handler_.Register("handModuleConstructor",
      base::Bind(&HandInstance::OnHandModuleConstructor,
                 base::Unretained(this)));
}

HandInstance::~HandInstance() {
  hand_ext_thread_.Stop();
}

void HandInstance::HandleMessage(const char* msg) {
  JSONStringValueDeserializer str_deserializer(msg);

  int error_code = 0;
  std::string error_message;
  scoped_ptr<base::Value> value(
      str_deserializer.Deserialize(&error_code, &error_message));
  CHECK(value.get());
  CHECK_EQ(0, error_code);
  CHECK(error_message.empty());

  hand_ext_thread_.message_loop()->PostTask(
      FROM_HERE,
      base::Bind(&HandInstance::OnHandleMessage,
                 base::Unretained(this),
                 base::Passed(&value)));
}

void HandInstance::OnHandleMessage(scoped_ptr<base::Value> msg) {
  DCHECK_EQ(hand_ext_thread_.message_loop(), base::MessageLoop::current());
  handler_.HandleMessage(msg.Pass());
}

void HandInstance::OnHandModuleConstructor(
    scoped_ptr<XWalkExtensionFunctionInfo> info) {
  DCHECK_EQ(hand_ext_thread_.message_loop(), base::MessageLoop::current());
  scoped_ptr<Params> params(Params::Create(*info->arguments()));

  scoped_ptr<BindingObject> obj(new HandModuleObject());
  store_.AddBindingObject(params->object_id, obj.Pass());
}

}  // namespace hand
}  // namespace realsense
