// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// EnhancedPhotography API
namespace depth_photo {
  enum PixelFormat {
    RGB32,
    DEPTH
  };

  dictionary Image {
    PixelFormat format;
    long width;
    long height;
    long[] data;
  };

  callback ImagePromise = void(Image image, DOMString error);
  callback Promise = void(DOMString success, DOMString error);

  interface Functions {
    static void queryReferenceImage(ImagePromise promise);
    static void queryOriginalImage(ImagePromise promise);
    static void queryDepthImage(ImagePromise promise);
    static void queryRawDepthImage(ImagePromise promise);
    static void setColorImage(Image image, Promise promise);
    static void setDepthImage(Image image, Promise promise);
  };
};
