// Copyright (c) 2015 Intel Corporation. All rights reserved.
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

#include "realsense/face_tracking/win/face_tracking_instance.h"

#include <string>

// This file is auto-generated by face_tracking.idl
#include "face_tracking.h"  // NOLINT

#include "base/json/json_string_value_serializer.h"
#include "realsense/face_tracking/win/face_tracking_object.h"

namespace realsense {
namespace face_tracking {

using namespace xwalk::common; // NOLINT
using realsense::jsapi::face_tracking::FaceTrackingConstructor::Params;

FaceTrackingInstance::FaceTrackingInstance()
    : handler_(this),
      store_(&handler_),
      ft_ext_thread_("FTExtensionThread") {
  ft_ext_thread_.Start();
  handler_.Register("faceTrackingConstructor",
      base::Bind(&FaceTrackingInstance::OnFaceTrackingConstructor,
                 base::Unretained(this)));
}

FaceTrackingInstance::~FaceTrackingInstance() {
  ft_ext_thread_.Stop();
}

void FaceTrackingInstance::HandleMessage(const char* msg) {
  JSONStringValueDeserializer str_deserializer(msg);

  int error_code = 0;
  std::string error_message;
  scoped_ptr<base::Value> value(
      str_deserializer.Deserialize(&error_code, &error_message));
  CHECK(value.get());
  CHECK_EQ(0, error_code);
  CHECK(error_message.empty());

  ft_ext_thread_.message_loop()->PostTask(
      FROM_HERE,
      base::Bind(&FaceTrackingInstance::OnHandleMessage,
                 base::Unretained(this),
                 base::Passed(&value)));
}

void FaceTrackingInstance::OnHandleMessage(scoped_ptr<base::Value> msg) {
  DCHECK_EQ(ft_ext_thread_.message_loop(), base::MessageLoop::current());
  handler_.HandleMessage(msg.Pass());
}

void FaceTrackingInstance::OnFaceTrackingConstructor(
    scoped_ptr<XWalkExtensionFunctionInfo> info) {
  DCHECK_EQ(ft_ext_thread_.message_loop(), base::MessageLoop::current());
  scoped_ptr<Params> params(Params::Create(*info->arguments()));

  scoped_ptr<BindingObject> obj(new FaceTrackingObject());
  store_.AddBindingObject(params->object_id, obj.Pass());
}

}  // namespace face_tracking
}  // namespace realsense
